# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodKeeperServer', '0002_auto_20170211_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
        migrations.AddField(
            model_name='userdata',
            name='provider_id',
            field=models.CharField(default='email', max_length=50),
            preserve_default=False,
        ),
    ]
